### ISSUE TITLE
Format XML removes blank lines

### ISSUE THREAD

**Issue by kennardconsulting** [ccancinos/rinzo-xml-editor#23]
Hi guys,

Thanks for the great work on Rinzo XML!

I have a small bug fix: when I open an XML file (such as pom.xml) and choose to 'reformat' (Ctrl+Shift+F) Rinzo removes any blank lines in my XML.

Could this be optional? I like putting blank lines between POM sections such as 'dependencies' and 'build' for clarity.

**Comment by ccancinos** [comment]
Hi!

Thank you very much for your feedback.

I'll like to ask you if you could add a little more information on issue like plugin version or an xml example because I can't reproduce it with a little test I made on 1.4.0 version using this [input file](https://github.com/ccancinos/rinzo-xml-editor/blob/master/ar.com.tadp.xml.rinzo.core.test/src/ar/com/tadp/xml/rinzo/core/model/visitor/formatExample.xml) which will generate this [formatted output](https://github.com/ccancinos/rinzo-xml-editor/blob/master/ar.com.tadp.xml.rinzo.core.test/src/ar/com/tadp/xml/rinzo/core/model/visitor/formatExampleExpected.xml) where you can see the preserved blank lines 16, 19 and 23.

Thanks!
Claudio

**Comment by kennardconsulting** [comment]
Apologies. I have just re-installed and am unable to reproduce. It's working great now!
